use rusqlite::Connection;

pub(super) fn initialize_schema(connection: &Connection) -> rusqlite::Result<()> {
    connection.execute_batch(
        r#"
        CREATE TABLE IF NOT EXISTS config (
            version INTEGER NOT NULL,
            IARU_REGION INTEGER NOT NULL DEFAULT 2 CHECK (IARU_REGION IN (1, 2, 3)),
            LOGIN_USER TEXT NOT NULL DEFAULT '',
            LOGIN_PASSWORD TEXT NOT NULL DEFAULT '',
            DXCLUSTER_ENABLED INTEGER NOT NULL DEFAULT 0 CHECK (DXCLUSTER_ENABLED IN (0, 1)),
            DXCLUSTER_HOST TEXT NOT NULL DEFAULT '',
            DXCLUSTER_PORT INTEGER NOT NULL DEFAULT 23 CHECK (DXCLUSTER_PORT >= 0 AND DXCLUSTER_PORT <= 65535),
            DXCLUSTER_CALLSIGN TEXT NOT NULL DEFAULT '',
            DXCLUSTER_MAX_AGE_MIN INTEGER NOT NULL DEFAULT 60 CHECK (DXCLUSTER_MAX_AGE_MIN >= 15 AND DXCLUSTER_MAX_AGE_MIN <= 360),
            DXCLUSTER_COMMANDS TEXT NOT NULL DEFAULT ''
        ) STRICT;

        CREATE TABLE IF NOT EXISTS logs (
            ID INTEGER PRIMARY KEY,
            NAME TEXT NOT NULL,
            CONTEST_ID TEXT NOT NULL,
            STATION_CALLSIGN TEXT NOT NULL,
            CONTEST_PARAMS_JSON TEXT NOT NULL
        ) STRICT;

        CREATE TABLE IF NOT EXISTS radios (
            ID INTEGER PRIMARY KEY,
            NAME TEXT NOT NULL,
            RADIO_KIND TEXT NOT NULL,
            TRANSPORT_KIND TEXT NOT NULL,
            TCP_HOST TEXT NOT NULL DEFAULT '',
            TCP_PORT INTEGER NOT NULL DEFAULT 0 CHECK (TCP_PORT >= 0 AND TCP_PORT <= 65535),
            SERIAL_PORT TEXT NOT NULL DEFAULT '',
            SERIAL_BAUD_RATE INTEGER NOT NULL DEFAULT 115200 CHECK (SERIAL_BAUD_RATE > 0),
            OPTIONS TEXT NOT NULL DEFAULT '',
            DATA_MODE TEXT NOT NULL,
            RTTY_MODE TEXT NOT NULL,
            DIGITAL_PROGRAM TEXT NOT NULL DEFAULT 'none' CHECK (DIGITAL_PROGRAM IN ('none', 'wsjtx', 'fldigi')),
            WSJTX_ENABLED INTEGER NOT NULL DEFAULT 0 CHECK (WSJTX_ENABLED IN (0, 1)),
            WSJTX_BIND_ADDRESS TEXT NOT NULL DEFAULT '127.0.0.1' CHECK (WSJTX_BIND_ADDRESS IN ('127.0.0.1', '0.0.0.0')),
            WSJTX_PORT INTEGER NOT NULL DEFAULT 2237 CHECK (WSJTX_PORT >= 1024 AND WSJTX_PORT <= 65535),
            WSJTX_MULTICAST_GROUP TEXT NOT NULL DEFAULT '',
            FLDIGI_DATA_ENABLED INTEGER NOT NULL DEFAULT 0 CHECK (FLDIGI_DATA_ENABLED IN (0, 1)),
            FLDIGI_RTTY_ENABLED INTEGER NOT NULL DEFAULT 0 CHECK (FLDIGI_RTTY_ENABLED IN (0, 1)),
            FLDIGI_HOST TEXT NOT NULL DEFAULT '127.0.0.1',
            FLDIGI_PORT INTEGER NOT NULL DEFAULT 7362 CHECK (FLDIGI_PORT >= 1024 AND FLDIGI_PORT <= 65535),
            FLRIG_ENABLED INTEGER NOT NULL DEFAULT 0 CHECK (FLRIG_ENABLED IN (0, 1)),
            FLRIG_PORT INTEGER NOT NULL DEFAULT 12345 CHECK (FLRIG_PORT >= 1024 AND FLRIG_PORT <= 65535),
            CW_TUNING_INCREMENT_HZ INTEGER NOT NULL DEFAULT 20 CHECK (CW_TUNING_INCREMENT_HZ > 0),
            SSB_TUNING_INCREMENT_HZ INTEGER NOT NULL DEFAULT 100 CHECK (SSB_TUNING_INCREMENT_HZ > 0),
            RIT_CLEAR_ON_LOG INTEGER NOT NULL DEFAULT 0 CHECK (RIT_CLEAR_ON_LOG IN (0, 1)),
            VOICE_INPUT_DEVICE_ID TEXT,
            VOICE_OUTPUT_DEVICE_ID TEXT,
            CW_KEYER_TYPE TEXT NOT NULL DEFAULT 'none',
            WINKEYER_SERIAL_PORT TEXT NOT NULL DEFAULT '',
            CW_SERIAL_PORT TEXT NOT NULL DEFAULT '',
            CW_SERIAL_BAUD_RATE INTEGER NOT NULL DEFAULT 9600 CHECK (CW_SERIAL_BAUD_RATE > 0),
            CW_SERIAL_LINE TEXT NOT NULL DEFAULT 'dtr',
            CW_MESSAGES TEXT NOT NULL,
            VOICE_MESSAGES TEXT NOT NULL,
            CONTROL_LOCATION TEXT NOT NULL DEFAULT 'backend' CHECK (CONTROL_LOCATION IN ('backend', 'client')),
            CLIENT_INSTANCE_ID TEXT,
            RADIO_WS_URL TEXT,
            CHECK (
                (CONTROL_LOCATION = 'backend' AND CLIENT_INSTANCE_ID IS NULL AND RADIO_WS_URL IS NULL)
                OR (
                    CONTROL_LOCATION = 'client'
                    AND CLIENT_INSTANCE_ID IS NOT NULL AND length(trim(CLIENT_INSTANCE_ID)) > 0
                    AND RADIO_WS_URL IS NOT NULL AND length(trim(RADIO_WS_URL)) > 0
                )
            ),
            CHECK (
                (DIGITAL_PROGRAM = 'wsjtx' AND WSJTX_ENABLED = 1)
                OR (DIGITAL_PROGRAM != 'wsjtx' AND WSJTX_ENABLED = 0)
            ),
            CHECK (
                (DIGITAL_PROGRAM = 'fldigi' AND FLDIGI_DATA_ENABLED = 1)
                OR (DIGITAL_PROGRAM != 'fldigi' AND FLDIGI_DATA_ENABLED = 0)
            )
        ) STRICT;

        CREATE TABLE IF NOT EXISTS qsos (
            ID INTEGER PRIMARY KEY,
            LOG_ID INTEGER NOT NULL REFERENCES logs(ID) ON DELETE CASCADE,
            QSO_DATE_TIME_ON INTEGER NOT NULL,
            STATION_CALLSIGN TEXT NOT NULL,
            OPERATOR TEXT,
            CONTEST_ID TEXT NOT NULL,
            CALL TEXT NOT NULL,
            BAND TEXT NOT NULL,
            FREQ INTEGER NOT NULL,
            MODE TEXT NOT NULL,
            RST_SENT INTEGER,
            RST_RCVD INTEGER,
            ARRL_SECT TEXT,
            CNTY TEXT,
            CQZ INTEGER,
            CONT TEXT,
            DXCC INTEGER,
            APP_LOG73_DXCC_PFX TEXT,
            GRIDSQUARE TEXT,
            MY_CNTY TEXT,
            MY_CONT TEXT,
            MY_CQ_ZONE INTEGER,
            MY_DXCC INTEGER,
            APP_LOG73_MY_DXCC_PFX TEXT,
            MY_GRIDSQUARE TEXT,
            MY_STATE TEXT,
            MY_ARRL_SECT TEXT,
            SRX INTEGER,
            SRX_STRING TEXT,
            STATE TEXT,
            STX INTEGER,
            STX_STRING TEXT,
            TX_PWR INTEGER,
            JSON TEXT
        ) STRICT;

        CREATE INDEX IF NOT EXISTS idx_qsos_log_id ON qsos(LOG_ID);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_radios_enabled_wsjtx_port
            ON radios(WSJTX_PORT) WHERE WSJTX_ENABLED = 1 AND CONTROL_LOCATION = 'backend';
        CREATE UNIQUE INDEX IF NOT EXISTS idx_radios_enabled_flrig_port
            ON radios(FLRIG_PORT) WHERE FLRIG_ENABLED = 1 AND CONTROL_LOCATION = 'backend';
        CREATE UNIQUE INDEX IF NOT EXISTS idx_radios_client_instance_id
            ON radios(CLIENT_INSTANCE_ID) WHERE CONTROL_LOCATION = 'client';

        CREATE TABLE IF NOT EXISTS log_serial_state (
            LOG_ID INTEGER NOT NULL REFERENCES logs(ID) ON DELETE CASCADE,
            FIELD_ADIF TEXT NOT NULL,
            NEXT_SERIAL INTEGER NOT NULL CHECK (NEXT_SERIAL > 0),
            PRIMARY KEY (LOG_ID, FIELD_ADIF)
        ) STRICT;
        "#,
    )?;

    let config_count: i64 =
        connection.query_row("SELECT COUNT(*) FROM config", [], |row| row.get(0))?;
    if config_count == 0 {
        connection.execute("INSERT INTO config (version) VALUES (1)", [])?;
    } else {
        connection.execute("UPDATE config SET version = 1", [])?;
    }

    Ok(())
}
